# Based on https://github.com/PrakashTrove/AWS-CodeBuild-NetCore/blob/master/buildspec.yml
# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
phases:   
  install:
    runtime-versions:
      dotnet: latest
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore PickEmLeague/PickEmLeague.csproj
      - dotnet tool install -g Amazon.ElasticBeanstalk.Tools
      
  build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - echo Build started on `date`
      - cd PickEmLeague/
      - dotnet eb package
    #   - dotnet publish -c release -o ./build_output PickEmLeague/PickEmLeague.csproj
      # - dotnet publish -c Debug -r linux-x64 --self-contained false PickEmLeague/PickEmLeague.csproj

artifacts:
  files:
    - PickEmLeague/bin/release/netcoreapp3.1/publish/*
    # - PickEmLeague\bin\Debug\netcoreapp3.1\linux-x64\publish\*
    # - build_output/**
    # - scripts/**/*
    # - appspec.yml
      
#   post_build:
#     commands:
#       - echo Publish started on `date`
#       # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
#       - dotnet publish -c Release -r linux-x64 --self-contained false PickEmLeague/PickEmLeague.csproj
      
# artifacts:
#   files:
#     - '**/*'
#   base-directory: ./bin/Release/netcoreapp3.1/linux-x64/publish/
#   discard-paths: no