/* tslint:disable */
/* eslint-disable */
/**
 * PickEmLeague
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import { User, UserFromJSON, UserToJSON } from "../models";

export interface UserPostRequest {
  user?: User;
}

/**
 *
 */
export class UserApi extends runtime.BaseAPI {
  /**
   */
  async userGetRaw(): Promise<runtime.ApiResponse<Array<User>>> {
    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request({
      path: `/User`,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    });

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(UserFromJSON)
    );
  }

  /**
   */
  async userGet(): Promise<Array<User>> {
    const response = await this.userGetRaw();
    return await response.value();
  }

  /**
   */
  async userPostRaw(
    requestParameters: UserPostRequest
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request({
      path: `/User`,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: UserToJSON(requestParameters.user),
    });

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async userPost(requestParameters: UserPostRequest): Promise<void> {
    await this.userPostRaw(requestParameters);
  }
}
