/* tslint:disable */
/* eslint-disable */
/**
 * PickEmLeague
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  GameResult,
  GameResultFromJSON,
  GameResultFromJSONTyped,
  GameResultToJSON,
} from "./";

/**
 *
 * @export
 * @interface Game
 */
export interface Game {
  /**
   *
   * @type {number}
   * @memberof Game
   */
  homeTeam?: number;
  /**
   *
   * @type {number}
   * @memberof Game
   */
  awayTeam?: number;
  /**
   *
   * @type {number}
   * @memberof Game
   */
  week?: number;
  /**
   *
   * @type {Date}
   * @memberof Game
   */
  gameTime?: Date;
  /**
   *
   * @type {GameResult}
   * @memberof Game
   */
  gameResult?: GameResult;
  /**
   *
   * @type {number}
   * @memberof Game
   */
  id?: number;
}

export function GameFromJSON(json: any): Game {
  return GameFromJSONTyped(json, false);
}

export function GameFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Game {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    homeTeam: !exists(json, "homeTeam") ? undefined : json["homeTeam"],
    awayTeam: !exists(json, "awayTeam") ? undefined : json["awayTeam"],
    week: !exists(json, "week") ? undefined : json["week"],
    gameTime: !exists(json, "gameTime")
      ? undefined
      : new Date(json["gameTime"]),
    gameResult: !exists(json, "gameResult")
      ? undefined
      : GameResultFromJSON(json["gameResult"]),
    id: !exists(json, "id") ? undefined : json["id"],
  };
}

export function GameToJSON(value?: Game | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    homeTeam: value.homeTeam,
    awayTeam: value.awayTeam,
    week: value.week,
    gameTime:
      value.gameTime === undefined ? undefined : value.gameTime.toISOString(),
    gameResult: GameResultToJSON(value.gameResult),
    id: value.id,
  };
}
