/* tslint:disable */
/* eslint-disable */
/**
 * PickEmLeague
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface MiscAdmin
 */
export interface MiscAdmin {
  /**
   *
   * @type {number}
   * @memberof MiscAdmin
   */
  currentWeek?: number;
  /**
   *
   * @type {number}
   * @memberof MiscAdmin
   */
  id?: number;
}

export function MiscAdminFromJSON(json: any): MiscAdmin {
  return MiscAdminFromJSONTyped(json, false);
}

export function MiscAdminFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MiscAdmin {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    currentWeek: !exists(json, "currentWeek") ? undefined : json["currentWeek"],
    id: !exists(json, "id") ? undefined : json["id"],
  };
}

export function MiscAdminToJSON(value?: MiscAdmin | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    currentWeek: value.currentWeek,
    id: value.id,
  };
}
