/* tslint:disable */
/* eslint-disable */
/**
 * PickEmLeague
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  UsersWeeklyScoreSummary,
  UsersWeeklyScoreSummaryFromJSON,
  UsersWeeklyScoreSummaryFromJSONTyped,
  UsersWeeklyScoreSummaryToJSON,
} from "./";

/**
 *
 * @export
 * @interface ScoreSummaryResponse
 */
export interface ScoreSummaryResponse {
  /**
   *
   * @type {number}
   * @memberof ScoreSummaryResponse
   */
  week?: number;
  /**
   *
   * @type {Array<UsersWeeklyScoreSummary>}
   * @memberof ScoreSummaryResponse
   */
  usersWeeklyScoreSummaries?: Array<UsersWeeklyScoreSummary> | null;
}

export function ScoreSummaryResponseFromJSON(json: any): ScoreSummaryResponse {
  return ScoreSummaryResponseFromJSONTyped(json, false);
}

export function ScoreSummaryResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ScoreSummaryResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    week: !exists(json, "week") ? undefined : json["week"],
    usersWeeklyScoreSummaries: !exists(json, "usersWeeklyScoreSummaries")
      ? undefined
      : json["usersWeeklyScoreSummaries"] === null
      ? null
      : (json["usersWeeklyScoreSummaries"] as Array<any>).map(
          UsersWeeklyScoreSummaryFromJSON
        ),
  };
}

export function ScoreSummaryResponseToJSON(
  value?: ScoreSummaryResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    week: value.week,
    usersWeeklyScoreSummaries:
      value.usersWeeklyScoreSummaries === undefined
        ? undefined
        : value.usersWeeklyScoreSummaries === null
        ? null
        : (value.usersWeeklyScoreSummaries as Array<any>).map(
            UsersWeeklyScoreSummaryToJSON
          ),
  };
}
