/* tslint:disable */
/* eslint-disable */
/**
 * PickEmLeague
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UserSeasonSummary
 */
export interface UserSeasonSummary {
  /**
   *
   * @type {number}
   * @memberof UserSeasonSummary
   */
  seasonScore?: number;
  /**
   *
   * @type {number}
   * @memberof UserSeasonSummary
   */
  correctPicks?: number;
}

export function UserSeasonSummaryFromJSON(json: any): UserSeasonSummary {
  return UserSeasonSummaryFromJSONTyped(json, false);
}

export function UserSeasonSummaryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserSeasonSummary {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    seasonScore: !exists(json, "seasonScore") ? undefined : json["seasonScore"],
    correctPicks: !exists(json, "correctPicks")
      ? undefined
      : json["correctPicks"],
  };
}

export function UserSeasonSummaryToJSON(value?: UserSeasonSummary | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    seasonScore: value.seasonScore,
    correctPicks: value.correctPicks,
  };
}
