/* tslint:disable */
/* eslint-disable */
/**
 * PickEmLeague
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './';

/**
 * 
 * @export
 * @interface UsersWeeklyScoreSummary
 */
export interface UsersWeeklyScoreSummary {
    /**
     * 
     * @type {User}
     * @memberof UsersWeeklyScoreSummary
     */
    user?: User;
    /**
     * 
     * @type {number}
     * @memberof UsersWeeklyScoreSummary
     */
    weekScore?: number;
    /**
     * 
     * @type {number}
     * @memberof UsersWeeklyScoreSummary
     */
    seasonScore?: number;
}

export function UsersWeeklyScoreSummaryFromJSON(json: any): UsersWeeklyScoreSummary {
    return UsersWeeklyScoreSummaryFromJSONTyped(json, false);
}

export function UsersWeeklyScoreSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersWeeklyScoreSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
        'weekScore': !exists(json, 'weekScore') ? undefined : json['weekScore'],
        'seasonScore': !exists(json, 'seasonScore') ? undefined : json['seasonScore'],
    };
}

export function UsersWeeklyScoreSummaryToJSON(value?: UsersWeeklyScoreSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserToJSON(value.user),
        'weekScore': value.weekScore,
        'seasonScore': value.seasonScore,
    };
}


