/* tslint:disable */
/* eslint-disable */
/**
 * PickEmLeague
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  WeekPickStatus,
  WeekPickStatusFromJSON,
  WeekPickStatusFromJSONTyped,
  WeekPickStatusToJSON,
} from "./";

/**
 *
 * @export
 * @interface UserWeekSummary
 */
export interface UserWeekSummary {
  /**
   *
   * @type {number}
   * @memberof UserWeekSummary
   */
  weekScore?: number;
  /**
   *
   * @type {WeekPickStatus}
   * @memberof UserWeekSummary
   */
  weekPickStatus?: WeekPickStatus;
  /**
   *
   * @type {number}
   * @memberof UserWeekSummary
   */
  correctPicks?: number;
  /**
   *
   * @type {number}
   * @memberof UserWeekSummary
   */
  place?: number;
}

export function UserWeekSummaryFromJSON(json: any): UserWeekSummary {
  return UserWeekSummaryFromJSONTyped(json, false);
}

export function UserWeekSummaryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserWeekSummary {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    weekScore: !exists(json, "weekScore") ? undefined : json["weekScore"],
    weekPickStatus: !exists(json, "weekPickStatus")
      ? undefined
      : WeekPickStatusFromJSON(json["weekPickStatus"]),
    correctPicks: !exists(json, "correctPicks")
      ? undefined
      : json["correctPicks"],
    place: !exists(json, "place") ? undefined : json["place"],
  };
}

export function UserWeekSummaryToJSON(value?: UserWeekSummary | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    weekScore: value.weekScore,
    weekPickStatus: WeekPickStatusToJSON(value.weekPickStatus),
    correctPicks: value.correctPicks,
    place: value.place,
  };
}
