/* tslint:disable */
/* eslint-disable */
/**
 * PickEmLeague
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  User,
  UserFromJSON,
  UserFromJSONTyped,
  UserToJSON,
  UserSeasonSummary,
  UserSeasonSummaryFromJSON,
  UserSeasonSummaryFromJSONTyped,
  UserSeasonSummaryToJSON,
  UserWeekSummary,
  UserWeekSummaryFromJSON,
  UserWeekSummaryFromJSONTyped,
  UserWeekSummaryToJSON,
} from "./";

/**
 *
 * @export
 * @interface UserSummary
 */
export interface UserSummary {
  /**
   *
   * @type {User}
   * @memberof UserSummary
   */
  user?: User;
  /**
   *
   * @type {UserWeekSummary}
   * @memberof UserSummary
   */
  weekSummary?: UserWeekSummary;
  /**
   *
   * @type {UserSeasonSummary}
   * @memberof UserSummary
   */
  seasonSummary?: UserSeasonSummary;
}

export function UserSummaryFromJSON(json: any): UserSummary {
  return UserSummaryFromJSONTyped(json, false);
}

export function UserSummaryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserSummary {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    user: !exists(json, "user") ? undefined : UserFromJSON(json["user"]),
    weekSummary: !exists(json, "weekSummary")
      ? undefined
      : UserWeekSummaryFromJSON(json["weekSummary"]),
    seasonSummary: !exists(json, "seasonSummary")
      ? undefined
      : UserSeasonSummaryFromJSON(json["seasonSummary"]),
  };
}

export function UserSummaryToJSON(value?: UserSummary | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    user: UserToJSON(value.user),
    weekSummary: UserWeekSummaryToJSON(value.weekSummary),
    seasonSummary: UserSeasonSummaryToJSON(value.seasonSummary),
  };
}
