/* tslint:disable */
/* eslint-disable */
/**
 * PickEmLeague
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface User
 */
export interface User {
  /**
   *
   * @type {string}
   * @memberof User
   */
  name?: string | null;
  /**
   *
   * @type {string}
   * @memberof User
   */
  username?: string | null;
  /**
   *
   * @type {string}
   * @memberof User
   */
  email?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  isAdmin?: boolean;
  /**
   *
   * @type {string}
   * @memberof User
   */
  passwordHash?: string | null;
  /**
   *
   * @type {string}
   * @memberof User
   */
  profilePic?: string | null;
  /**
   *
   * @type {string}
   * @memberof User
   */
  picType?: string | null;
  /**
   *
   * @type {number}
   * @memberof User
   */
  id?: number;
}

export function UserFromJSON(json: any): User {
  return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): User {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, "name") ? undefined : json["name"],
    username: !exists(json, "username") ? undefined : json["username"],
    email: !exists(json, "email") ? undefined : json["email"],
    isAdmin: !exists(json, "isAdmin") ? undefined : json["isAdmin"],
    passwordHash: !exists(json, "passwordHash")
      ? undefined
      : json["passwordHash"],
    profilePic: !exists(json, "profilePic") ? undefined : json["profilePic"],
    picType: !exists(json, "picType") ? undefined : json["picType"],
    id: !exists(json, "id") ? undefined : json["id"],
  };
}

export function UserToJSON(value?: User | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    username: value.username,
    email: value.email,
    isAdmin: value.isAdmin,
    passwordHash: value.passwordHash,
    profilePic: value.profilePic,
    picType: value.picType,
    id: value.id,
  };
}
