/* tslint:disable */
/* eslint-disable */
/**
 * PickEmLeague
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface WeatherForecast
 */
export interface WeatherForecast {
  /**
   *
   * @type {Date}
   * @memberof WeatherForecast
   */
  date?: Date;
  /**
   *
   * @type {number}
   * @memberof WeatherForecast
   */
  temperatureC?: number;
  /**
   *
   * @type {number}
   * @memberof WeatherForecast
   */
  readonly temperatureF?: number;
  /**
   *
   * @type {string}
   * @memberof WeatherForecast
   */
  summary?: string | null;
}

export function WeatherForecastFromJSON(json: any): WeatherForecast {
  return WeatherForecastFromJSONTyped(json, false);
}

export function WeatherForecastFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): WeatherForecast {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    date: !exists(json, "date") ? undefined : new Date(json["date"]),
    temperatureC: !exists(json, "temperatureC")
      ? undefined
      : json["temperatureC"],
    temperatureF: !exists(json, "temperatureF")
      ? undefined
      : json["temperatureF"],
    summary: !exists(json, "summary") ? undefined : json["summary"],
  };
}

export function WeatherForecastToJSON(value?: WeatherForecast | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    date: value.date === undefined ? undefined : value.date.toISOString(),
    temperatureC: value.temperatureC,
    summary: value.summary,
  };
}
