/* tslint:disable */
/* eslint-disable */
/**
 * PickEmLeague
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import { User, UserFromJSON, UserFromJSONTyped, UserToJSON } from "./";

/**
 *
 * @export
 * @interface WeekWinnerResponse
 */
export interface WeekWinnerResponse {
  /**
   *
   * @type {User}
   * @memberof WeekWinnerResponse
   */
  winner?: User;
  /**
   *
   * @type {boolean}
   * @memberof WeekWinnerResponse
   */
  foundWinner?: boolean;
}

export function WeekWinnerResponseFromJSON(json: any): WeekWinnerResponse {
  return WeekWinnerResponseFromJSONTyped(json, false);
}

export function WeekWinnerResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): WeekWinnerResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    winner: !exists(json, "winner") ? undefined : UserFromJSON(json["winner"]),
    foundWinner: !exists(json, "foundWinner") ? undefined : json["foundWinner"],
  };
}

export function WeekWinnerResponseToJSON(
  value?: WeekWinnerResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    winner: UserToJSON(value.winner),
    foundWinner: value.foundWinner,
  };
}
