/* tslint:disable */
/* eslint-disable */
/**
 * PickEmLeague
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import { MiscAdmin, MiscAdminFromJSON, MiscAdminToJSON } from "../models";

export interface MiscAdminUpdateMiscAdminPutRequest {
  miscAdmin?: MiscAdmin;
}

/**
 *
 */
export class MiscAdminApi extends runtime.BaseAPI {
  /**
   */
  async miscAdminGetMiscAdminGetRaw(): Promise<runtime.ApiResponse<MiscAdmin>> {
    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request({
      path: `/MiscAdmin/getMiscAdmin`,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    });

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      MiscAdminFromJSON(jsonValue)
    );
  }

  /**
   */
  async miscAdminGetMiscAdminGet(): Promise<MiscAdmin> {
    const response = await this.miscAdminGetMiscAdminGetRaw();
    return await response.value();
  }

  /**
   */
  async miscAdminUpdateMiscAdminPutRaw(
    requestParameters: MiscAdminUpdateMiscAdminPutRequest
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json-patch+json";

    const response = await this.request({
      path: `/MiscAdmin/updateMiscAdmin`,
      method: "PUT",
      headers: headerParameters,
      query: queryParameters,
      body: MiscAdminToJSON(requestParameters.miscAdmin),
    });

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async miscAdminUpdateMiscAdminPut(
    requestParameters: MiscAdminUpdateMiscAdminPutRequest
  ): Promise<void> {
    await this.miscAdminUpdateMiscAdminPutRaw(requestParameters);
  }
}
