/* tslint:disable */
/* eslint-disable */
/**
 * PickEmLeague
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    UsersWeeklyScoreSummary,
    UsersWeeklyScoreSummaryFromJSON,
    UsersWeeklyScoreSummaryToJSON,
} from '../models';

export interface ScoreSummaryGetScoreSummaryGetRequest {
    week?: number;
}

/**
 * 
 */
export class ScoreSummaryApi extends runtime.BaseAPI {

    /**
     */
    async scoreSummaryGetScoreSummaryGetRaw(requestParameters: ScoreSummaryGetScoreSummaryGetRequest): Promise<runtime.ApiResponse<Array<UsersWeeklyScoreSummary>>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.week !== undefined) {
            queryParameters['week'] = requestParameters.week;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/ScoreSummary/getScoreSummary`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UsersWeeklyScoreSummaryFromJSON));
    }

    /**
     */
    async scoreSummaryGetScoreSummaryGet(requestParameters: ScoreSummaryGetScoreSummaryGetRequest): Promise<Array<UsersWeeklyScoreSummary>> {
        const response = await this.scoreSummaryGetScoreSummaryGetRaw(requestParameters);
        return await response.value();
    }

}
