/* tslint:disable */
/* eslint-disable */
/**
 * PickEmLeague
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import { Team, TeamFromJSON, TeamToJSON } from "../models";

/**
 *
 */
export class TeamApi extends runtime.BaseAPI {
  /**
   */
  async teamGetRaw(): Promise<runtime.ApiResponse<Array<Team>>> {
    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request({
      path: `/Team`,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    });

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(TeamFromJSON)
    );
  }

  /**
   */
  async teamGet(): Promise<Array<Team>> {
    const response = await this.teamGetRaw();
    return await response.value();
  }
}
