/* tslint:disable */
/* eslint-disable */
/**
 * PickEmLeague
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import { User, UserFromJSON, UserToJSON } from "../models";

export interface UserDeleteDeleteRequest {
  id?: number;
}

export interface UserGetGetRequest {
  id?: number;
}

export interface UserUpdatePutRequest {
  user?: User;
}

/**
 *
 */
export class UserApi extends runtime.BaseAPI {
  /**
   */
  async userCreatePostRaw(): Promise<runtime.ApiResponse<User>> {
    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request({
      path: `/User/create`,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
    });

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UserFromJSON(jsonValue)
    );
  }

  /**
   */
  async userCreatePost(): Promise<User> {
    const response = await this.userCreatePostRaw();
    return await response.value();
  }

  /**
   */
  async userDeleteDeleteRaw(
    requestParameters: UserDeleteDeleteRequest
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: runtime.HTTPQuery = {};

    if (requestParameters.id !== undefined) {
      queryParameters["id"] = requestParameters.id;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request({
      path: `/User/delete`,
      method: "DELETE",
      headers: headerParameters,
      query: queryParameters,
    });

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async userDeleteDelete(
    requestParameters: UserDeleteDeleteRequest
  ): Promise<void> {
    await this.userDeleteDeleteRaw(requestParameters);
  }

  /**
   */
  async userGetAllGetRaw(): Promise<runtime.ApiResponse<Array<User>>> {
    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request({
      path: `/User/get-all`,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    });

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(UserFromJSON)
    );
  }

  /**
   */
  async userGetAllGet(): Promise<Array<User>> {
    const response = await this.userGetAllGetRaw();
    return await response.value();
  }

  /**
   */
  async userGetGetRaw(
    requestParameters: UserGetGetRequest
  ): Promise<runtime.ApiResponse<User>> {
    const queryParameters: runtime.HTTPQuery = {};

    if (requestParameters.id !== undefined) {
      queryParameters["id"] = requestParameters.id;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request({
      path: `/User/get`,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    });

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UserFromJSON(jsonValue)
    );
  }

  /**
   */
  async userGetGet(requestParameters: UserGetGetRequest): Promise<User> {
    const response = await this.userGetGetRaw(requestParameters);
    return await response.value();
  }

  /**
   */
  async userUpdatePutRaw(
    requestParameters: UserUpdatePutRequest
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json-patch+json";

    const response = await this.request({
      path: `/User/update`,
      method: "PUT",
      headers: headerParameters,
      query: queryParameters,
      body: UserToJSON(requestParameters.user),
    });

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async userUpdatePut(requestParameters: UserUpdatePutRequest): Promise<void> {
    await this.userUpdatePutRaw(requestParameters);
  }
}
