/* tslint:disable */
/* eslint-disable */
/**
 * PickEmLeague
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import { User, UserFromJSON, UserToJSON } from "../models";

export interface UserDeleteRequest {
  id?: number;
}

export interface UserGetUserGetRequest {
  id?: number;
}

export interface UserUpdateUserPutRequest {
  user?: User;
}

/**
 *
 */
export class UserApi extends runtime.BaseAPI {
  /**
   */
  async userCreateUserPostRaw(): Promise<runtime.ApiResponse<User>> {
    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request({
      path: `/User/create-user`,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
    });

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UserFromJSON(jsonValue)
    );
  }

  /**
   */
  async userCreateUserPost(): Promise<User> {
    const response = await this.userCreateUserPostRaw();
    return await response.value();
  }

  /**
   */
  async userDeleteRaw(
    requestParameters: UserDeleteRequest
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: runtime.HTTPQuery = {};

    if (requestParameters.id !== undefined) {
      queryParameters["id"] = requestParameters.id;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request({
      path: `/User`,
      method: "DELETE",
      headers: headerParameters,
      query: queryParameters,
    });

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async userDelete(requestParameters: UserDeleteRequest): Promise<void> {
    await this.userDeleteRaw(requestParameters);
  }

  /**
   */
  async userGetAllUsersGetRaw(): Promise<runtime.ApiResponse<Array<User>>> {
    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request({
      path: `/User/get-all-users`,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    });

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(UserFromJSON)
    );
  }

  /**
   */
  async userGetAllUsersGet(): Promise<Array<User>> {
    const response = await this.userGetAllUsersGetRaw();
    return await response.value();
  }

  /**
   */
  async userGetUserGetRaw(
    requestParameters: UserGetUserGetRequest
  ): Promise<runtime.ApiResponse<User>> {
    const queryParameters: runtime.HTTPQuery = {};

    if (requestParameters.id !== undefined) {
      queryParameters["id"] = requestParameters.id;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request({
      path: `/User/get-user`,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    });

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UserFromJSON(jsonValue)
    );
  }

  /**
   */
  async userGetUserGet(
    requestParameters: UserGetUserGetRequest
  ): Promise<User> {
    const response = await this.userGetUserGetRaw(requestParameters);
    return await response.value();
  }

  /**
   */
  async userUpdateUserPutRaw(
    requestParameters: UserUpdateUserPutRequest
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request({
      path: `/User/update-user`,
      method: "PUT",
      headers: headerParameters,
      query: queryParameters,
      body: UserToJSON(requestParameters.user),
    });

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async userUpdateUserPut(
    requestParameters: UserUpdateUserPutRequest
  ): Promise<void> {
    await this.userUpdateUserPutRaw(requestParameters);
  }
}
