# This is a basic workflow to help you get started with Actions
name: Build and Deploy Master

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.1.x']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Installing NPM
        run: npm install

      - name: Building application
        run: dotnet build
        
      - name: Publish
        run: npm run publish
        
      - name: Package
        run: npm run package
        
      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: List
        run: cd publishes && ls
        
      - name: Beanstalk Deploy my app
        uses: einaregilsson/beanstalk-deploy@v4
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
          aws_secret_key: ${{secrets.AWS_SECRET_KEY}}
          application_name: PickEmLeague2021
          environment_name: PickEmLeague2021-env
          region: us-east-1
          version_label: "pickemleague2021-${{ steps.format-time.outputs.replaced }}" #Using timestamp create on earlier step
          deployment_package: publishes/deploy.zip

      - name: Deployed successfully!
        run: echo App deployed to ELB

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      
      - name: Npm Install Frontend
        run: npm install
        working-directory: PickEmLeagueFrontEnd/ClientApp
      
      - name: Build Frontend
        run: npm run build
        working-directory: PickEmLeagueFrontEnd/ClientApp

      - name: Deploy static site to S3 bucket
        run: aws s3 sync build/* s3://2021pickemleague-react
        working-directory: PickEmLeagueFrontEnd/ClientApp
